image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  before_script:
  - apk update && apk add nodejs npm
  script:
  - npm i && hugo -D --gc
  artifacts:
    paths:
    - public
  only:
  - main